[2024-07-10T09:01:54.869+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2024-07-10T09:01:39.096710+00:00 [queued]>
[2024-07-10T09:01:54.874+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2024-07-10T09:01:39.096710+00:00 [queued]>
[2024-07-10T09:01:54.876+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-07-10T09:01:54.878+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-07-10T09:01:54.878+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-07-10T09:01:54.888+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2024-07-10 09:01:39.096710+00:00
[2024-07-10T09:01:54.902+0000] {standard_task_runner.py:55} INFO - Started process 9019 to run task
[2024-07-10T09:01:54.908+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2024-07-10T09:01:39.096710+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpw2gnba14']
[2024-07-10T09:01:54.911+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask store_user
[2024-07-10T09:01:54.947+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user manual__2024-07-10T09:01:39.096710+00:00 [running]> on host ee2fbeb286fd
[2024-07-10T09:01:54.995+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2024-07-10T09:01:39.096710+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-10T09:01:39.096710+00:00
[2024-07-10T09:01:54.997+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2024-07-10T09:01:55.003+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-07-10T09:01:55.009+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 33, in _store_user
    filename="/tmp/processed_user.csv",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "lastname"
CONTEXT:  COPY users, line 2: "com"

[2024-07-10T09:01:55.035+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20240710T090139, start_date=20240710T090154, end_date=20240710T090155
[2024-07-10T09:01:55.070+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 23 for task store_user (missing data for column "lastname"
CONTEXT:  COPY users, line 2: "com"
; 9019)
[2024-07-10T09:01:55.090+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-07-10T09:01:55.110+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
